apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gm2uy5bhz-go 
  janus-idp.io/tekton: gm2uy5bhz-go
  backstage.io/kubernetes-id: gm2uy5bhz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gm2uy5bhz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml